version: "3.12"

volumes:
  pg_data:

services:

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 5

  backend:
    env_file: .env
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 && poetry run python manage.py migrate && poetry run python manage.py runserver"
